#include "stdafx.h"
#include "dispconst.h"

BEGIN_CONST_MAP(smartscrollconsts_)
	DEF_CONST_CUSTOM(L"SmartScrollConsts", 0)

	// common.h
	DEF_CONST(SSP_NAME)
	DEF_CONST(SSP_NAME_EX)

	DEF_CONST(SSP_BUTTON1)
	DEF_CONST(SSP_BUTTON2)
	DEF_CONST(SSP_BUTTON3)
	DEF_CONST(SSP_BUTTON4)
	DEF_CONST(SSP_BUTTON5)
	DEF_CONST(SSP_BUTTON6)
	DEF_CONST(SSP_BUTTON7)
	DEF_CONST(SSP_BUTTON8)
	DEF_CONST(SSP_BUTTON_WHEEL)

	DEF_CONST(SSP_BUTTON1_DOWN)
	DEF_CONST(SSP_BUTTON1_UP)
	DEF_CONST(SSP_BUTTON2_DOWN)
	DEF_CONST(SSP_BUTTON2_UP)
	DEF_CONST(SSP_BUTTON3_DOWN)
	DEF_CONST(SSP_BUTTON3_UP)
	DEF_CONST(SSP_BUTTON4_DOWN)
	DEF_CONST(SSP_BUTTON4_UP)
	DEF_CONST(SSP_BUTTON5_DOWN)
	DEF_CONST(SSP_BUTTON5_UP)
	DEF_CONST(SSP_BUTTON6_DOWN)
	DEF_CONST(SSP_BUTTON6_UP)
	DEF_CONST(SSP_BUTTON7_DOWN)
	DEF_CONST(SSP_BUTTON7_UP)
	DEF_CONST(SSP_BUTTON8_DOWN)
	DEF_CONST(SSP_BUTTON8_UP)
	DEF_CONST(SSP_BUTTON_WHEEL_DOWN)
	DEF_CONST(SSP_BUTTON_WHEEL_UP)

	DEF_CONST(SSP_WHEEL_FW)
	DEF_CONST(SSP_WHEEL_BK)

	DEF_CONST(SSP_SCROLL_NONE)
	DEF_CONST(SSP_SCROLL_UP)
	DEF_CONST(SSP_SCROLL_DOWN)
	DEF_CONST(SSP_SCROLL_LEFT)
	DEF_CONST(SSP_SCROLL_RIGHT)

	// enum SSP_STATUS
	DEF_CONST(SSP_FALSE)
	DEF_CONST(SSP_TRUE)
	DEF_CONST(SSP_SHOW_HIDE)
	DEF_CONST(SSP_SWITCH_PROTOCOL)
	DEF_CONST(SSP_TIMER)
	
	// sspfunc.h
	DEF_CONST(SSP_AUTHOR_LENGTH)
	DEF_CONST(SSP_ICON_SIZE)
	DEF_CONST(SSP_ICON_BASE)
	DEF_CONST(SSP_STRING_BASE)

	DEF_CONST(SSP_BUTTON_DOWN)
	DEF_CONST(SSP_BUTTON_UP)

	DEF_CONST(SSP_BUFFER_LENGTH)
	DEF_CONST(SSP_KEY_MAX)
	DEF_CONST(SSP_KEY_TEXT_MAX)

	DEF_CONST(SSP_BUTTON_NUM)

	DEF_CONST_CUSTOM(L"SSP_SMART_SCROLL", 118)

END_CONST_MAP()
